dream-faster/fold-wrappers

LICENSE
=> chore(Docs): updated Licence

.github/workflows/docs.yaml, codecov.yml, docs/index.md, mkdocs.yml, pyproject.toml
=> feature(Docs): added mkdocs

.github/workflows/flake8.yaml, .pre-commit-config.yaml, src/fold_models/statsforecast.py, tests/test_statsforecast.py
=> chore(Project): update precommit hooks

.github/workflows/test-xgboost.yaml, src/fold_models/__init__.py, src/fold_models/statsforecast.py, src/fold_models/xgboost.py, tests/test_statsforecast.py, tests/test_xgboost.py
=> feature(XGBoost): added XGB wrapper

.github/workflows/publish.yaml
=> feature(CI): publish workflow

README.md, docs/index.md
=> feature(Docs): updated

src/fold_models/__init__.py, src/fold_models/statsforecast.py, src/fold_models/xgboost.py, tests/test_statsforecast.py, tests/test_xgboost.py
=> fix(API): updated to follow new fold Model API

.github/workflows/test-statsmodels.yaml, README.md, pyproject.toml, src/fold_models/statsmodels.py, tests/test_statsforecast.py, tests/test_statsmodels.py, tests/utils.py
=> feature(Models): Added test and initial wrapper for ``statsmodels`` library (https://github.com/statsmodels/statsmodels).

.github/workflows/test-sktime.yaml, README.md, pyproject.toml, src/fold_models/sktime.py, src/fold_models/statsforecast.py, tests/test_sktime.py, tests/utils.py
=> feature(Models): Added wrapper for ``sktime`` (https://github.com/sktime/sktime)

src/fold_models/sktime.py
=> feature(SKTime): Sktime now depends on the length of X rather than its indices

src/fold_models/__init__.py, src/fold_models/sktime.py, src/fold_models/statsforecast.py, src/fold_models/statsmodels.py, src/fold_models/xgboost.py, tests/test_sktime.py
Closes #33
Closes #31 
Closes #32
=> refactor(All): made `use_exogenous` Optional

README.md
=> fix(Docs): Added badges to README for each test and fixed typo.

.github/workflows/test-prophet.yaml, README.md, pyproject.toml, src/fold_models/__init__.py, src/fold_models/prophet.py, tests/test_prophet.py
=> feature(Prophet): added WrapProphet class

README.md, src/fold_models/prophet.py, src/fold_models/sktime.py, src/fold_models/statsforecast.py, src/fold_models/statsmodels.py, src/fold_models/xgboost.py, tests/test_prophet.py
=> feature(Docs): added online update column, made prophet wrapper updateable

pyproject.toml, pytest.ini
=> fix(Tests): move pytest config to pyproject.toml

pyproject.toml
Fixes torch version under 2.0.0.
=> fix(NeuralForecast): fix torch version

mkdocs.yml, tests/test_neuralforecast.py
=> fix(NeuralForecast): use the `step` for `input_size`

src/fold_models/neuralforecast.py, tests/test_neuralforecast.py
=> fix(NeuralForecast): frequency should be set from X

src/fold_models/baseline.py, src/fold_models/neuralforecast.py, src/fold_models/prophet.py, src/fold_models/sktime.py, src/fold_models/statsforecast.py, src/fold_models/statsmodels.py, src/fold_models/xgboost.py
=> fix(Models): added requires_X to Properties

src/fold_models/baseline.py
=> fix(Baseline): path to base transformation changed in `fold`

README.md
=> fix(Docs): This will let us display badges on our website without it breaking to multiple lines.

README.md, docs/images/logo.svg
=> chore(Docs): Update readme with fold-models and fold-wrappers.

LICENSE
=> chore(Docs): Updated license to be MIT

README.md
=> fix(Docs): updated README Licence section

pyproject.toml
=> feature(Project): added versioning fields

README.md
=> chore(Docs): Calendly link change.

.github/workflows/bump-version.yaml
=> feature(CI): added `bump-version` workflow

.vscode/settings.json, src/fold_wrappers/lightgbm.py, src/fold_wrappers/xgboost.py, tests/test_lightgbm.py, tests/test_xgboost.py
Closes #78 
Closes #79 
Closes #80
=> feature(XGBoost & LightGBM): return probabilities, made them Tunable

.github/workflows/test-arch.yaml, .github/workflows/test-lightgbm.yaml, .github/workflows/test-neuralforecast.yaml, .github/workflows/test-prophet.yaml, .github/workflows/test-sktime.yaml, .github/workflows/test-statsforecast.yaml, .github/workflows/test-statsmodels.yaml, .github/workflows/test-xgboost.yaml
=> fix(CI): use latest commit from `fold/main` to run the tests

src/fold_wrappers/arch.py, src/fold_wrappers/lightgbm.py, src/fold_wrappers/statsmodels.py, src/fold_wrappers/xgboost.py
=> fix(Models): ability to pass in custom name, propagate it when cloning

src/fold_wrappers/arch.py, src/fold_wrappers/lightgbm.py, src/fold_wrappers/neuralforecast.py, src/fold_wrappers/prophet.py, src/fold_wrappers/sktime.py, src/fold_wrappers/statsforecast.py, src/fold_wrappers/statsmodels.py, src/fold_wrappers/xgboost.py
=> fix(Models): removed default `properties` property

src/fold_wrappers/xgboost.py, tests/test_xgboost.py
=> feature(XGBoost): added set_class_weights property
